name: release

on:
  push:
    branches: [ main ]

jobs:
  print_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variable
        run: echo "Environment Variable: ${{ env.KTEST_SECRET }}"
  release-to-dockerhub:
    runs-on: ubuntu-latest
    environment: 
      name: CD
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - id: parse_version
      name: Parse version
      run: echo "::set-output name=cli_version::$(sed -n -e "/^__version__/p" cdf_fabric_replicator/__init__.py | cut -c 16- | sed -e 's/^"//' -e 's/"$//')"

    - name: Echo version
      run: echo ${{ steps.parse_version.outputs.cli_version }}

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip cognite-extractor-manager poetry

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: ./build/Dockerfile
        tags: cognite/cdf-fabric-replicator:${{ steps.parse_version.outputs.cli_version }}
